FROM golang:1.24.5


WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download
RUN go mod tidy
RUN go install -mod=mod github.com/githubnemo/CompileDaemon@v1.4.0
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.3
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.3
RUN go install go.uber.org/mock/mockgen@v0.5.2

# Install protobuf tools
RUN apt-get update && apt-get install -y protobuf-compiler && rm -rf /var/lib/apt/lists/*
RUN go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.36.7
RUN go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.5.1
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-grpc-gateway@v2.27.1
RUN go install github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2@v2.27.1

COPY . .

RUN chmod +x /app/*

EXPOSE 4000
EXPOSE 9090

CMD CompileDaemon --build="go build -race main.go" --command="./main serve"


