FROM golang:1.24.5


WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download
RUN go mod tidy
RUN go install -mod=mod github.com/githubnemo/CompileDaemon@v1.4.0
RUN go install github.com/swaggo/swag/cmd/swag@v1.16.3
RUN go install github.com/sqlc-dev/sqlc/cmd/sqlc@v1.27.0
RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.18.3
RUN go install go.uber.org/mock/mockgen@v0.5.2

COPY . .

RUN chmod +x /app/*

EXPOSE 4000

CMD CompileDaemon --build="go build -race main.go" --command="./main serve"


