// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: block_session.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const blockSession = `-- name: BlockSession :exec
UPDATE sessions 
SET is_blocked = true, updated_at = now()
WHERE id = $1
`

func (q *Queries) BlockSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, blockSession, id)
	return err
}
