// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: create_exchange_rate.sql

package db

import (
	"context"
	"database/sql"
)

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (
  from_currency,
  to_currency,
  rate
) VALUES (
  $1, $2, $3
) RETURNING id, from_currency, to_currency, rate::float8, created_at
`

type CreateExchangeRateParams struct {
	FromCurrency string `json:"from_currency"`
	ToCurrency   string `json:"to_currency"`
	Rate         string `json:"rate"`
}

type CreateExchangeRateRow struct {
	ID           int64        `json:"id"`
	FromCurrency string       `json:"from_currency"`
	ToCurrency   string       `json:"to_currency"`
	Rate         float64      `json:"rate"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (CreateExchangeRateRow, error) {
	row := q.queryRow(ctx, q.createExchangeRateStmt, createExchangeRate, arg.FromCurrency, arg.ToCurrency, arg.Rate)
	var i CreateExchangeRateRow
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
