// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_exchange_rate.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const createExchangeRate = `-- name: CreateExchangeRate :one
INSERT INTO exchange_rates (
  from_currency,
  to_currency,
  rate
) VALUES (
  $1, $2, $3
) RETURNING id, from_currency, to_currency, rate, created_at
`

type CreateExchangeRateParams struct {
	FromCurrency string          `json:"from_currency"`
	ToCurrency   string          `json:"to_currency"`
	Rate         decimal.Decimal `json:"rate"`
}

func (q *Queries) CreateExchangeRate(ctx context.Context, arg CreateExchangeRateParams) (ExchangeRate, error) {
	row := q.db.QueryRow(ctx, createExchangeRate, arg.FromCurrency, arg.ToCurrency, arg.Rate)
	var i ExchangeRate
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
