// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: create_transfer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const createTransfer = `-- name: CreateTransfer :one
INSERT INTO transfers (
  from_account_id,
  to_account_id,
  amount,
  converted_amount,
  exchange_rate,
  from_currency,
  to_currency
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, from_account_id, to_account_id, amount, converted_amount, exchange_rate, from_currency, to_currency, created_at
`

type CreateTransferParams struct {
	FromAccountID   int64           `json:"from_account_id"`
	ToAccountID     int64           `json:"to_account_id"`
	Amount          decimal.Decimal `json:"amount"`
	ConvertedAmount decimal.Decimal `json:"converted_amount"`
	ExchangeRate    decimal.Decimal `json:"exchange_rate"`
	FromCurrency    pgtype.Text     `json:"from_currency"`
	ToCurrency      pgtype.Text     `json:"to_currency"`
}

func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) (Transfer, error) {
	row := q.db.QueryRow(ctx, createTransfer,
		arg.FromAccountID,
		arg.ToAccountID,
		arg.Amount,
		arg.ConvertedAmount,
		arg.ExchangeRate,
		arg.FromCurrency,
		arg.ToCurrency,
	)
	var i Transfer
	err := row.Scan(
		&i.ID,
		&i.FromAccountID,
		&i.ToAccountID,
		&i.Amount,
		&i.ConvertedAmount,
		&i.ExchangeRate,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.CreatedAt,
	)
	return i, err
}
