// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: get_user_hashed_password.sql

package db

import (
	"context"
)

const getUserHashedPassword = `-- name: GetUserHashedPassword :one
SELECT hashed_password FROM users
WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserHashedPassword(ctx context.Context, username string) (string, error) {
	row := q.db.QueryRow(ctx, getUserHashedPassword, username)
	var hashed_password string
	err := row.Scan(&hashed_password)
	return hashed_password, err
}
