// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: get_exchange_rate.sql

package db

import (
	"context"
	"database/sql"
)

const getExchangeRate = `-- name: GetExchangeRate :one
SELECT id, from_currency, to_currency, rate::float8, created_at FROM exchange_rates
WHERE from_currency = $1 AND to_currency = $2
LIMIT 1
`

type GetExchangeRateParams struct {
	FromCurrency string `json:"from_currency"`
	ToCurrency   string `json:"to_currency"`
}

type GetExchangeRateRow struct {
	ID           int64        `json:"id"`
	FromCurrency string       `json:"from_currency"`
	ToCurrency   string       `json:"to_currency"`
	Rate         float64      `json:"rate"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) GetExchangeRate(ctx context.Context, arg GetExchangeRateParams) (GetExchangeRateRow, error) {
	row := q.queryRow(ctx, q.getExchangeRateStmt, getExchangeRate, arg.FromCurrency, arg.ToCurrency)
	var i GetExchangeRateRow
	err := row.Scan(
		&i.ID,
		&i.FromCurrency,
		&i.ToCurrency,
		&i.Rate,
		&i.CreatedAt,
	)
	return i, err
}
