// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: list_exchange_rates.sql

package db

import (
	"context"
	"database/sql"
)

const listExchangeRates = `-- name: ListExchangeRates :many
SELECT id, from_currency, to_currency, rate::float8, created_at FROM exchange_rates
ORDER BY from_currency, to_currency
`

type ListExchangeRatesRow struct {
	ID           int64        `json:"id"`
	FromCurrency string       `json:"from_currency"`
	ToCurrency   string       `json:"to_currency"`
	Rate         float64      `json:"rate"`
	CreatedAt    sql.NullTime `json:"created_at"`
}

func (q *Queries) ListExchangeRates(ctx context.Context) ([]ListExchangeRatesRow, error) {
	rows, err := q.query(ctx, q.listExchangeRatesStmt, listExchangeRates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExchangeRatesRow{}
	for rows.Next() {
		var i ListExchangeRatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FromCurrency,
			&i.ToCurrency,
			&i.Rate,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
