// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: update_session.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const updateSession = `-- name: UpdateSession :exec
UPDATE sessions 
SET 
  id = $2,
  refresh_token = $3,
  expires_at = $4,
  updated_at = now()
WHERE id = $1
`

type UpdateSessionParams struct {
	ID           uuid.UUID `json:"id"`
	ID_2         uuid.UUID `json:"id_2"`
	RefreshToken string    `json:"refresh_token"`
	ExpiresAt    time.Time `json:"expires_at"`
}

func (q *Queries) UpdateSession(ctx context.Context, arg UpdateSessionParams) error {
	_, err := q.db.Exec(ctx, updateSession,
		arg.ID,
		arg.ID_2,
		arg.RefreshToken,
		arg.ExpiresAt,
	)
	return err
}
